// Generated by `npm run cf-typegen`
// Run `npm run cf-typegen` after wrangler.toml changes.
interface Env {
  CORE_API_URL: string;
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  POSTHOG_API_KEY?: string;
  LS_CHECKOUT_URL?: string;
  LS_CUSTOMER_PORTAL_URL?: string;
}

// Virtual module type stub — actual module generated at build time by @react-router/dev
declare module "virtual:react-router/server-build" {
  import type { ServerBuild } from "react-router";
  const build: ServerBuild;
  export = build;
}
